import java.net.URI
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/9.3.1/userguide/custom_plugins.html in the Gradle documentation.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`
    `kotlin-dsl`
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

gradlePlugin {
    // Define the plugin
    val xspec by plugins.creating {
        id = "io.werkstatt.xspec.gradle-plugin"
        implementationClass = "io.werkstatt.xspec.xspec_gradle.XspecGradlePlugin"
    }
}

// Add a source set for the functional test suite
val functionalTestSourceSet = sourceSets.create("functionalTest") {
}

configurations["functionalTestImplementation"].extendsFrom(configurations["testImplementation"])
configurations["functionalTestRuntimeOnly"].extendsFrom(configurations["testRuntimeOnly"])

// Add a task to run the functional tests
val functionalTest by tasks.registering(Test::class) {
    testClassesDirs = functionalTestSourceSet.output.classesDirs
    classpath = functionalTestSourceSet.runtimeClasspath
    useJUnitPlatform()
}

gradlePlugin.testSourceSets.add(functionalTestSourceSet)


tasks.register("bundle-xspec") {
    val xspecVersion = project.property("xspecVersion") as String
    val resourcePath = project.layout.projectDirectory.dir("src/main/resources/io/werkstatt/xspec/xspec_gradle")
    val downloadPath = resourcePath.file("xspec-${xspecVersion}.zip").asFile.toPath()
    val versionFile = resourcePath.file("xspec-version.txt").asFile

    doLast {
        versionFile.parentFile.mkdirs()

        val req = HttpRequest.newBuilder()
            .uri(URI("https://github.com/xspec/xspec/archive/refs/tags/v${xspecVersion}.zip"))
            .GET()
            .build()

        val client = HttpClient.newBuilder()
            .followRedirects(HttpClient.Redirect.ALWAYS)
            .build()
        val response = client.send(req, HttpResponse.BodyHandlers.ofFile(downloadPath))
        if (response.statusCode() != 200) {
            throw GradleException("Unexpected status code: ${response.statusCode()}")
        }

        versionFile.writeText(xspecVersion)
    }
}

tasks.named<Task>("check") {
    // Run the functional tests as part of `check`
    dependsOn(functionalTest)
}

tasks.named<Test>("test") {
    // Use JUnit Jupiter for unit tests.
    useJUnitPlatform()
}
