/*
 * This source file was generated by the Gradle 'init' task
 */
package io.werkstatt.xspec.xspec_gradle

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'io.werkstatt.xspec.xspec_gradle.greeting' plugin.
 */
class XspecGradlePluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("io.werkstatt.xspec.gradle-plugin")

        // Verify the result
        assertNotNull(project.tasks.findByName("xspec-compile"))
    }
}
