/*
 * This source file was generated by the Gradle 'init' task
 */
package io.werkstatt.xspec.xspec_gradle

import java.io.File
import kotlin.test.Test
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.io.TempDir
import java.nio.file.Paths
import kotlin.io.path.absolute

/**
 * A simple functional test for the 'io.werkstatt.xspec.gradle-plugin' plugin.
 */
class XspecGradlePluginFunctionalTest {
    @field:TempDir
    lateinit var projectDir: File

    private val buildFile by lazy { projectDir.resolve("build.gradle.kts") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle.kts") }
    private val specFixturesDir by lazy { Paths.get("src/functionalTest/resources").absolute() }

    @Test fun `can run compile task`() {
        // Set up the test build
        settingsFile.writeText("")
        buildFile.writeText("""
          repositories {
            mavenCentral()
          }
          plugins {
              id("io.werkstatt.xspec.gradle-plugin")
          }
          
          dependencies {
            xspec("net.sf.saxon:Saxon-HE:12.9")
          }
          
          xspec {
              xspecDir = layout.projectDirectory.dir("${specFixturesDir.resolve("xslt/apply-templates")}")
              suiteFiles.from(layout.projectDirectory.file("${specFixturesDir.resolve("xslt/apply-templates/simple.xspec")}"))
          }
        """.trimIndent())

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("xspec")
        runner.withProjectDir(projectDir)
        runner.withDebug(true)
        val result = runner.build()

        // Verify the result
        assertFalse(result.output.contains("FAILED"))
    }
}
